# SPDX-FileCopyrightText: 2023 David Runge <dvzrv@archlinux.org>
# SPDX-License-Identifier: CC0-1.0

# NOTE: we override the yaml language server support here to have specific ansible language server support
[[language]]
name = "yaml"
scope = "source.ansible"
file-types = ["yaml", "yml"]
injection-regex = "yml|yaml"
roots = [".ansible-lint", "ansible.cfg"]
comment-token = "#"
language-server = { command = "ansible-language-server", args = ["--stdio"] }
indent = { tab-width = 2, unit = "  " }
